apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: asegui-v1
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: asegui
        version: v1
    spec:
      containers:
      - name: asegui
        image: iad.ocir.io/orasenatdctocloudcorp01/asecotcontainergui:4.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: asegui
  labels:
    app: asegui
spec:
  ports:
  - port: 8080
    name: http
  selector:
    app: asegui